title: Kevin Sharp # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an aspiring data scientist with a background in software development. I want to use my proficiency in mathematics to help people and businesses operate more efficiently and am currently growing my skills in Python, SQL, and related technologies to better meet those needs. I also bring prior experience working with C#, Xamarin, and Unity to the table. Through all of these skills, I have also demonstrated my ability to learn quickly and adapt to ever-changing technologies. 
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-sharp24/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
